=== CarmeloAlcCoy/PracticaArSo/examen-arso/ejercicios/bookle/schema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT actividad (titulo, descripcion?, profesor, email?, agenda+) >
<!ATTLIST actividad 
		id NMTOKEN #REQUIRED>
	
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT descripcion (#PCDATA) >
<!ELEMENT profesor (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT agenda (fecha, turno+) >
<!ELEMENT fecha (#PCDATA) >

<!ELEMENT turno (horario, reserva?) >
<!ELEMENT horario (#PCDATA) >

<!ELEMENT reserva (alumno, email?)>
<!ELEMENT alumno (#PCDATA) >
<!ATTLIST reserva 
		id NMTOKEN #REQUIRED>

=== CarmeloAlcCoy/PracticaArSo/examen-arso/bookle-rest/bookle/bookle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE actividad SYSTEM "../bookle/schema.dtd" >
<actividad id="25">
  <titulo>Entrevistas Pr√°cticas Arso 2019</titulo>
  <profesor>Un profesor</profesor>
  <email>profesor.uno@um.es</email>
  <agenda>
    <fecha>2019-2-27</fecha>
    <turno>
      <horario>15:00-16:00</horario>
      <reserva id="k28">
        <alumno>Pedro</alumno>
        <email>pedro.alcaraz@um.es</email>
      </reserva>
    </turno>
    <turno>
      <horario>A las 16</horario>
    </turno>
  </agenda>
  <agenda>
  <fecha>2019-2-28</fecha>
    <turno>
      <horario>15:00-16:00</horario>
      <reserva id="k29">
        <alumno>Kobe Bryant</alumno>
        <email>kobe.the.best@um.es</email>
      </reserva>
    </turno>
  
  </agenda>
</actividad>
