=== CarmeloAlcCoy/PracticaArSo/examen-arso/ejercicios/xml/schema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT city (name, country, population, position, urlBDpedia?, urlWikipedia?, meteoInfo?, interestPlace*) >
<!ATTLIST city 
		id CDATA #REQUIRED
		updatedOn CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT population (#PCDATA)>

<!ELEMENT position (lat, lng)>
<!ELEMENT lat (#PCDATA)>
<!ELEMENT lng (#PCDATA)>

<!ELEMENT urlBDpedia (#PCDATA)>
<!ELEMENT urlWikipedia (#PCDATA)>

<!ELEMENT meteoInfo (stationName, temperature, clouds)>
<!ATTLIST meteoInfo
		takenOn CDATA #REQUIRED>

<!ELEMENT stationName (#PCDATA)>
<!ELEMENT temperature (#PCDATA)>
<!ELEMENT clouds (#PCDATA)>

<!ELEMENT interestPlace (name)>
<!ATTLIST interestPlace 
	id CDATA #REQUIRED>

=== CarmeloAlcCoy/PracticaArSo/AlcarazCoy-Carmelo/xml/exampleDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE city SYSTEM "schema.dtd" >
<city updatedOn="2012-03-04" id="2520058">
	<name>Cartagena</name>
	<country>Spain</country>
	<population>211966</population>
	<position>
		<lat>37.60512</lat>
		<lng>-0.98623</lng>
	</position>
	<urlBDpedia>http://dbpedia.org/resource/Cartagena%2C_Spain</urlBDpedia>
	<urlWikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Spain</urlWikipedia>
	<meteoInfo takenOn="2019-02-04 12:00:00">
		<stationName>International airport of the Region of Murcia</stationName>
		<temperature>13</temperature>
		<clouds>clouds and visibility OK</clouds>
	</meteoInfo>
	<interestPlace id="10860321">
		<name>Parque Maestranza de Artilleria</name>
	</interestPlace>
	<interestPlace id="10280776">
		<name>Museo Hist√≥rico Militar de Cartagena</name>
	</interestPlace>
</city>
