=== CarmeloAlcCoy/PracticaArSo/AlcarazCoy-Carmelo/xml/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/Schema"
	xmlns:tns="http://www.example.org/Schema"
	elementFormDefault="qualified">

	<element name="city">
		<complexType>
			<sequence>
				<element name="name" type="string" />
				<element name="geonamesid" type="tns:tipo_geonameid" />
				<element name="country" type="string" />
				<element name="population" type="positiveInteger" />
				<element name="position" type="tns:Position" />
				<element name="urlBDpedia" minOccurs="0" type="tns:url" />
				<element name="urlWikipedia" minOccurs="0" type="tns:url" />
				<element name="meteoInfo" minOccurs="0"
					type="tns:MeteoInfo" />
				<element name="interestPlace" minOccurs="0"
					maxOccurs="unbounded" type="tns:InterestPlace" />
			</sequence>
			<attribute name="updatedOn" type="date" />
		</complexType>
	</element>
	<simpleType name="tipo_geonameid">
		<restriction base="string">
			<pattern value="[0-9]+" />
		</restriction>
	</simpleType>
	<simpleType name="url">
		<restriction base="string">
			<pattern
				value="(http(s)?:\/\/)?(www\.)?[a-zA-Z0-9\.-]+\.[a-zA-Z0-9]+(\/[a-zA-Z0-9\.\-_~:/?#\[\]$@%!&amp;&apos;\(\)\*\+,;=]+)*" />
		</restriction>
	</simpleType>
	<complexType name="Position">
		<sequence>
			<element name="lat">
				<simpleType>
					<restriction base="decimal">
						<maxInclusive value="90" />
						<minInclusive value="-90" />
					</restriction>
				</simpleType>
			</element>
			<element name="lng">
				<simpleType>
					<restriction base="decimal">
						<maxInclusive value="180" />
						<minInclusive value="-180" />
					</restriction>
				</simpleType>
			</element>
		</sequence>
	</complexType>
	<complexType name="MeteoInfo">
		<sequence>
			<element name="stationName" type="string" />
			<element name="temperature" type="decimal" />
			<element name="clouds" type="string" />
		</sequence>
		<attribute name="takenOn" type="dateTime" />
	</complexType>

	<complexType name="InterestPlace">
		<sequence>
			<element name="name" type="string" />
			<element name="id" type="tns:tipo_geonameid" />
		</sequence>
	</complexType>
</schema>

=== CarmeloAlcCoy/PracticaArSo/AlcarazCoy-Carmelo/xml/exampleXMLSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<city xmlns="http://www.example.org/Schema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/Schema Schema.xsd " 
	id="2520058"
	updatedOn="2012-03-04">
	<name>Cartagena</name>
	<country>Spain</country>
	<population>211966</population>
	<position>
		<lat>37.60512</lat>
		<lng>-0.98623</lng>
	</position>
	<urlBDpedia>http://dbpedia.org/resource/Cartagena%2C_Spain</urlBDpedia>
	<urlWikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Spain</urlWikipedia>
	<meteoInfo takenOn="2019-02-04T12:00:00">
		<stationName>International airport of the Region of Murcia</stationName>
		<temperature>13</temperature>
		<clouds>clouds and visibility OK</clouds>
	</meteoInfo>
	<interestPlace>
		<name>Parque Maestranza de Artilleria</name>
		<id>10860321</id>
	</interestPlace>
	<interestPlace>
		<name>Museo Hist√≥rico Militar de Cartagena</name>
		<id>10280776</id>
	</interestPlace>
</city>

=== CarmeloAlcCoy/PracticaArSo/AlcarazCoy-Carmelo/xml/2520058.xml
<?xml version="1.0" ?><city xmlns="http://www.example.org/Schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Schema Schema.xsd " updatedOn="2012-03-04"><name>Cartagena</name><geonamesid>2520058</geonamesid><country></country><population>211996</population><position><lat>37.60512</lat><lng>-0.98623</lng></position><urlBDpedia>http://dbpedia.org/resource/Cartagena%2C_Spain</urlBDpedia><urlWikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Spain</urlWikipedia><meteoInfo takenOn="2019-03-30T11:00:00"><stationName>International airport of the Region of Murcia</stationName><temperature>11.0</temperature><clouds>clouds and visibility OK</clouds></meteoInfo><interestPlace><name>Parque Maestranza de Artilleria</name><id>10860321</id></interestPlace><interestPlace><name>Museo Histórico Militar de Cartagena</name><id>10280776</id></interestPlace><interestPlace><name>Parque Arqueológico Cerro del Molinete</name><id>10280775</id></interestPlace><interestPlace><name>Barrio del Foro Romano</name><id>10280774</id></interestPlace><interestPlace><name>SERCOTEL Carlos III</name><id>6505996</id></interestPlace><interestPlace><name>Sercotel Alfonso Xiii Ex-Best Western</name><id>10170453</id></interestPlace><interestPlace><name>Sercotel Alfonso XIII</name><id>6483755</id></interestPlace><interestPlace><name>Plaza San Francisco</name><id>10400375</id></interestPlace><interestPlace><name>HUSA CARTAGONOVA Hotel &amp; Spa</name><id>6482678</id></interestPlace></city>

=== CarmeloAlcCoy/PracticaArSo/AlcarazCoy-Carmelo/xml-bd/3687238.xml
<?xml version="1.0" ?>
<city xmlns="http://www.example.org/Schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Schema Schema.xsd "
	updatedOn="2018-04-20">
	<name>Cartagena</name>
	<geonamesid>3687238</geonamesid>
	<country>M</country>
	<population>952024</population>
	<position>
		<lat>10.39972</lat>
		<lng>-75.51444</lng>
	</position>
	<urlBDpedia>http://dbpedia.org/resource/Cartagena%2C_Colombia</urlBDpedia>
	<urlWikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Colombia</urlWikipedia>
	<meteoInfo takenOn="2019-03-30T11:00:00">
		<stationName>Cartagena / Rafael Nunez</stationName>
		<temperature>28.0</temperature>
		<clouds>few clouds</clouds>
	</meteoInfo>
	<interestPlace>
		<name>Acueducto Cartagena</name>
		<id>3687237</id>
	</interestPlace>
	<interestPlace>
		<name>Barrio El Prado</name>
		<id>3689126</id>
	</interestPlace>
	<interestPlace>
		<name>Amberes</name>
		<id>3689976</id>
	</interestPlace>
	<interestPlace>
		<name>Armenia</name>
		<id>3689554</id>
	</interestPlace>
	<interestPlace>
		<name>Bruselas</name>
		<id>3688474</id>
	</interestPlace>
	<interestPlace>
		<name>Movich Hotel Cartagena De Indias Slh</name>
		<id>9612088</id>
	</interestPlace>
	<interestPlace>
		<name>Cartagena Water Treatment Plant</name>
		<id>9222770</id>
	</interestPlace>
	<interestPlace>
		<name>Lomas de Mariï¿½n</name>
		<id>3675258</id>
	</interestPlace>
	<interestPlace>
		<name>Hotel Avenida Buenos Aires</name>
		<id>10233251</id>
	</interestPlace>
</city>

=== CarmeloAlcCoy/PracticaArSo/practica-arso/AlcarazCoy-Carmelo/xml/2520058.xml
<?xml version="1.0" encoding="UTF-8"?>
<city xmlns="http://www.example.org/Schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Schema/ciudades Schema.xsd" id="2520058" updatedOn="2012-03-04">
  <name>Cartagena</name>
  <country>Spain</country>
  <population>211996</population>
  <position>
    <lat>37.60512</lat>
    <lng>-0.98623</lng>
  </position>
  <urlBDpedia>http://dbpedia.org/resource/Cartagena%2C_Spain</urlBDpedia>
  <urlWikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Spain</urlWikipedia>
  <meteoInfo takenOn="2019-05-16T09:30:00">
    <stationName>International airport of the Region of Murcia</stationName>
    <temperature>20.0</temperature>
    <clouds>clouds and visibility OK</clouds>
  </meteoInfo>
  <interestPlace>
    <name>Parque Maestranza de Artilleria</name>
    <id>10860321</id>
  </interestPlace>
  <interestPlace>
    <name>Museo Histórico Militar de Cartagena</name>
    <id>10280776</id>
  </interestPlace>
  <interestPlace>
    <name>Parque Arqueológico Cerro del Molinete</name>
    <id>10280775</id>
  </interestPlace>
  <interestPlace>
    <name>Barrio del Foro Romano</name>
    <id>10280774</id>
  </interestPlace>
  <interestPlace>
    <name>SERCOTEL Carlos III</name>
    <id>6505996</id>
  </interestPlace>
  <interestPlace>
    <name>Sercotel Alfonso Xiii Ex-Best Western</name>
    <id>10170453</id>
  </interestPlace>
  <interestPlace>
    <name>Sercotel Alfonso XIII</name>
    <id>6483755</id>
  </interestPlace>
  <interestPlace>
    <name>Plaza San Francisco</name>
    <id>10400375</id>
  </interestPlace>
  <interestPlace>
    <name>HUSA CARTAGONOVA Hotel &amp; Spa</name>
    <id>6482678</id>
  </interestPlace>
  <book>
    <title>El habla de Cartagena</title>
    <id>http://www.google.com/books/feeds/volumes/1iuJz2Ku9YQC</id>
    <isbn>ISBN:8476840187</isbn>
    <img>http://books.google.com/books/content?id=1iuJz2Ku9YQC&amp;printsec=frontcover&amp;img=1&amp;zoom=5&amp;edge=curl&amp;source=gbs_gdata</img>
    <ulrGoogleBooks>http://books.google.com/books?id=1iuJz2Ku9YQC&amp;dq=Cartagena&amp;source=gbs_gdata</ulrGoogleBooks>
  </book>
</city>

=== CarmeloAlcCoy/PracticaArSo/AlcarazCoy-Carmelo/xml-bd/2514891.xml
<?xml version="1.0" encoding="UTF-8"?>
<city xmlns="http://www.example.org/Schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Schema Schema.xsd " id="2514891" updatedOn="2012-12-15">
  <name>Lorca</name>
  <country>Spain</country>
  <population>91906</population>
  <position>
    <lat>37.67119</lat>
    <lng>-1.7017</lng>
  </position>
  <urlBDpedia>http://dbpedia.org/resource/Lorca%2C_Spain</urlBDpedia>
  <urlWikipedia>https://en.wikipedia.org/wiki/Lorca%2C_Spain</urlWikipedia>
  <meteoInfo takenOn="2019-04-02T05:00:00">
    <stationName>Murcia / Alcantarilla</stationName>
    <temperature>21.0</temperature>
    <clouds>few clouds</clouds>
  </meteoInfo>
  <interestPlace>
    <name>Parroquia San Crist√≥bal</name>
    <id>10342002</id>
  </interestPlace>
  <interestPlace>
    <name>Iglesia del Carmen</name>
    <id>10342001</id>
  </interestPlace>
  <interestPlace>
    <name>Museo Azul de la Semana Santa - MASS</name>
    <id>10342005</id>
  </interestPlace>
  <interestPlace>
    <name>Plaza de Colon</name>
    <id>10342008</id>
  </interestPlace>
  <interestPlace>
    <name>Teatro Guerra</name>
    <id>10285032</id>
  </interestPlace>
  <interestPlace>
    <name>Lorca Bus Station</name>
    <id>8436046</id>
  </interestPlace>
  <interestPlace>
    <name>Lorca Sutullena Railway Station</name>
    <id>8436045</id>
  </interestPlace>
  <interestPlace>
    <name>Plaza Calderon de la Barca</name>
    <id>10342006</id>
  </interestPlace>
  <interestPlace>
    <name>Parroquia de San Mateo</name>
    <id>10342007</id>
  </interestPlace>
</city>
